// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TGInterview.ProductService.Infrastructure.Data.Context;

#nullable disable

namespace TGInterview.ProductService.Api.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TGInterview.ProductService.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4923846e-08dd-4300-9d65-08b0d35e7f79"),
                            CreatedDate = new DateTime(2022, 12, 4, 22, 55, 53, 128, DateTimeKind.Utc).AddTicks(3881),
                            IsActive = true,
                            Name = "Laptop"
                        });
                });

            modelBuilder.Entity("TGInterview.ProductService.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c88a64e4-b9e0-469a-9250-12727b26ad94"),
                            CategoryId = new Guid("4923846e-08dd-4300-9d65-08b0d35e7f79"),
                            CreatedDate = new DateTime(2022, 12, 4, 22, 55, 53, 128, DateTimeKind.Utc).AddTicks(4443),
                            ImagePath = "https://productimages.hepsiburada.net/s/251/444-444/110000233748628.jpg",
                            IsActive = true,
                            Name = "Lenovo V15 Intel Core i5 10210U 8GB 512GB SSD MX330 15.6\" FHD Windows 10 Home Taşınabilir Bilgisayar 82NB003GTX",
                            Price = 11999.00m
                        },
                        new
                        {
                            Id = new Guid("eb03d02b-455d-4005-8120-8f4158e0f5cb"),
                            CategoryId = new Guid("4923846e-08dd-4300-9d65-08b0d35e7f79"),
                            CreatedDate = new DateTime(2022, 12, 4, 22, 55, 53, 128, DateTimeKind.Utc).AddTicks(4449),
                            ImagePath = "https://productimages.hepsiburada.net/s/155/550/110000111868185.jpg/format:webp",
                            IsActive = true,
                            Name = "Lenovo V15 G2 Itl Intel Core i5 1135G7 8GB 512GB SSD Windows 10 Home 15.6\" FHD Taşınabilir Bilgisayar 82KB00HUTX",
                            Price = 11999.00m
                        },
                        new
                        {
                            Id = new Guid("a2e19377-ebea-41de-9c8c-5b5083ed884a"),
                            CategoryId = new Guid("4923846e-08dd-4300-9d65-08b0d35e7f79"),
                            CreatedDate = new DateTime(2022, 12, 4, 22, 55, 53, 128, DateTimeKind.Utc).AddTicks(4454),
                            ImagePath = "https://productimages.hepsiburada.net/s/268/550/110000253796405.jpg/format:webp",
                            IsActive = true,
                            Name = "Lenovo V14 ITL Gen2 Intel Core i5 1135G7 8GB 512GB SSD Windows 10 Home 14\" FHD Taşınabilir Bilgisayar 82KA0027TX",
                            Price = 10999.00m
                        },
                        new
                        {
                            Id = new Guid("43895cbf-526b-4277-8a1b-0d53ff5d9f55"),
                            CategoryId = new Guid("4923846e-08dd-4300-9d65-08b0d35e7f79"),
                            CreatedDate = new DateTime(2022, 12, 4, 22, 55, 53, 128, DateTimeKind.Utc).AddTicks(4459),
                            ImagePath = "https://productimages.hepsiburada.net/s/174/550/110000137999718.jpg/format:webp",
                            IsActive = true,
                            Name = "Asus X509FA-BR951T Intel Core i3 10110U 4GB 256GB SSD Windows 10 Home 15.6\" HD Taşınabilir Bilgisayar",
                            Price = 7979.00m
                        },
                        new
                        {
                            Id = new Guid("2942ae60-7848-4340-af62-2bc25a5ef4a9"),
                            CategoryId = new Guid("4923846e-08dd-4300-9d65-08b0d35e7f79"),
                            CreatedDate = new DateTime(2022, 12, 4, 22, 55, 53, 128, DateTimeKind.Utc).AddTicks(4463),
                            ImagePath = "https://productimages.hepsiburada.net/s/67/550/110000008473669.jpg/format:webp",
                            IsActive = true,
                            Name = "Lenovo ThinkPad E15 Gen 2 Intel Core i7 1165G7 32GB 1TB SSD MX450 Windows 10 Pro 15.6\" FHD Taşınabilir Bilgisayar 20TDF01J00A20",
                            Price = 24499.99m
                        },
                        new
                        {
                            Id = new Guid("c2ac0654-011c-49f4-a52d-c7a64c6c6b84"),
                            CategoryId = new Guid("4923846e-08dd-4300-9d65-08b0d35e7f79"),
                            CreatedDate = new DateTime(2022, 12, 4, 22, 55, 53, 128, DateTimeKind.Utc).AddTicks(4468),
                            ImagePath = "https://productimages.hepsiburada.net/s/136/550/110000088054418.jpg/format:webp",
                            IsActive = true,
                            Name = "Hometech Alfa 470C Intel Celeron N4020 4GB 128GB SSD Windows 10 Home 14.1\" HD Taşınabilir Bilgisayar",
                            Price = 3649.00m
                        },
                        new
                        {
                            Id = new Guid("39ee5ede-a044-4bf2-9fd9-d85a54014285"),
                            CategoryId = new Guid("4923846e-08dd-4300-9d65-08b0d35e7f79"),
                            CreatedDate = new DateTime(2022, 12, 4, 22, 55, 53, 128, DateTimeKind.Utc).AddTicks(4473),
                            ImagePath = "https://productimages.hepsiburada.net/s/206/550/110000182831041.jpg/format:webp",
                            IsActive = true,
                            Name = "Hometech Alfa 470C Intel Celeron N4020 4GB 128GB SSD Windows 10 Home 14.1\" Hd Gold Taşınabilir Bilgisayar",
                            Price = 3699.00m
                        },
                        new
                        {
                            Id = new Guid("d959b7bc-1e34-4af2-831d-ca8f68f6e0d9"),
                            CategoryId = new Guid("4923846e-08dd-4300-9d65-08b0d35e7f79"),
                            CreatedDate = new DateTime(2022, 12, 4, 22, 55, 53, 128, DateTimeKind.Utc).AddTicks(4477),
                            ImagePath = "https://productimages.hepsiburada.net/s/43/550/10788533862450.jpg/format:webp",
                            IsActive = true,
                            Name = "Lenovo V14 IlL Intel Core i5 1035G1 8GB 256GB SSD Windows 10 Home 14\" FHD Taşınabilir Bilgisayar 82C400A8TX",
                            Price = 9584.55m
                        },
                        new
                        {
                            Id = new Guid("c4b67628-53de-4123-987e-dfb606dc5f19"),
                            CategoryId = new Guid("4923846e-08dd-4300-9d65-08b0d35e7f79"),
                            CreatedDate = new DateTime(2022, 12, 4, 22, 55, 53, 128, DateTimeKind.Utc).AddTicks(4483),
                            ImagePath = "https://productimages.hepsiburada.net/s/54/550/11196750659634.jpg/format:webp",
                            IsActive = true,
                            Name = "i-Life Zed Air CX5 Intel Core i5 5257U 8GB 256GB SSD Windows 10 Home 15.6\" FHD Taşınabilir Bilgisayar NTBTILWBi5158256",
                            Price = 6699.00m
                        });
                });

            modelBuilder.Entity("TGInterview.ProductService.Domain.Entities.Product", b =>
                {
                    b.HasOne("TGInterview.ProductService.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
